### ISSUE TITLE
CMakeFiles/temp.dir/build.make:92: recipe for target 'CMakeFiles/temp.dir/home/ghadeer/Desktop/ifrit/ifrit-4.1.2/src/ifrit-4.1.2/configure/ishellnew.cpp.o' failed

### ISSUE THREAD

**Issue by ghadeeralsheshakly** [srg-kostyrko/ifrit#1]
Hello,
I have been trying to build a program called ifrit.
I have already downloaded, VTK and QT5 as required but still I am getting this error:
![screenshot from 2018-04-18 22-27-02](https://user-images.githubusercontent.com/28873310/39088026-24efdc52-4579-11e8-8ead-893473d30503.png)

**Comment by srg-kostyrko** [comment]
Hi,

you added the issue to the wrong repository.

I assume you tried to build this one https://sites.google.com/site/ifrithome/. Seems there is no repo for it on github and you should send bugs to email.
